### ISSUE TITLE
MaybeSimpleCaseClosure broken on multi-character strings

### ISSUE THREAD

**Issue by waldemarhorwat** [tc39/proposal-regexp-set-notation#48]
*MaybeSimpleCaseClosure* only computes the case closure on single-character strings and passes other strings unchanged. This looks like it might be intentional, but it's also incorrect. Here's why.

`/[\q{k}&&\q{K}]/vi` will accept `k`, `K`, and the Kelvin symbol.

`/[\q{kk}&&\q{Kk}]/vi` will accept nothing. It should accept all variations of two k's of any case.

**Comment by markusicu** [comment]
We had discussed and resolved this with Waldemar a few weeks ago without looking at this GitHub issue here. We chose the second approach. Case-folding a set with replace each set element (consisting of any number of characters) with its Simple_Case_Folding equivalent, and the code point complement starts from a set of characters that don't case-fold, rather than all code points.
